export const UPDATE_LIBRARIES = 'UPDATE_LIBRARIES';
export const UPDATE_LIBRARIES_RAW = 'UPDATE_LIBRARIES_RAW';
export const LIBRARIES_REQUESTED = 'LIBRARIES_REQUESTED';
export const LIBRARIES_RECEIVED = 'LIBRARIES_RECEIVED';
export const LIBRARIES_REQUEST_FAILED = 'LIBRARIES_REQUEST_FAILED';
