export const USER_RECEIVED = 'USER_RECEIVED';
export const USER_REQUESTED = 'USER_REQUESTED';
export const USER_REQUEST_FAILED = 'USER_REQUEST_FAILED';
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_RECEIVED = 'LOGIN_RECEIVED';
export const LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED';
