// Libraries
export const FETCH_LIBRARIES_REQUEST = 'FETCH_LIBRARIES_REQUEST';
export const FETCH_LIBRARIES_SUCCESS = 'FETCH_LIBRARIES_SUCCESS';
export const FETCH_LIBRARIES_FAILURE = 'FETCH_LIBRARIES_FAILURE';
export const SEARCH_LIBRARIES = 'SEARCH_LIBRARIES';

// Profiles
export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';

// MyBooks
export const FETCH_MYBOOKS_REQUEST = 'FETCH_MYBOOKS_REQUEST';
export const FETCH_MYBOOKS_SUCCESS = 'FETCH_MYBOOKS_SUCCESS';
export const FETCH_MYBOOKS_FAILURE = 'FETCH_MYBOOKS_FAILURE';
export const ADD_NEWBOOK_REQUEST = 'ADD_NEWBOOK_REQUEST';
export const ADD_NEWBOOK_SUCCESS = 'ADD_NEWBOOK_SUCCESS';
export const ADD_NEWBOOK_FAILURE = 'ADD_NEWBOOK_FAILURE';
export const ADD_FORM_CLASS = 'ADD_FORM_CLASS';
export const REMOVE_FORM_CLASS = 'REMOVE_FORM_CLASS';
export const DELETE_BOOK_REQUEST = 'DELETE_BOOK_REQUEST';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE';
export const UNDO_DELETE_BOOK_REQUEST = 'UNDO_DELETE_BOOK_REQUEST';
export const UNDO_DELETE_BOOK_SUCCESS = 'UNDO_DELETE_BOOK_SUCCESS';
export const UNDO_DELETE_BOOK_FAILURE = 'UNDO_DELETE_BOOK_FAILURE';
export const TOOGLE_AVAILABLE_BOOK_REQUEST = 'TOOGLE_AVAILABLE_BOOK_REQUEST';
export const TOOGLE_AVAILABLE_BOOK_SUCCESS = 'TOOGLE_AVAILABLE_BOOK_SUCCESS';
export const TOOGLE_AVAILABLE_BOOK_FAILURE = 'TOOGLE_AVAILABLE_BOOK_FAILURE';
export const EDIT_BOOK_REQUEST = 'EDIT_BOOK_REQUEST';
export const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS';
export const EDIT_BOOK_FAILURE = 'EDIT_BOOK_FAILURE';

// Talks
export const FETCH_TALKS_REQUEST = 'FETCH_TALKS_REQUEST';
export const FETCH_TALKS_SUCCESS = 'FETCH_TALKS_SUCCESS';
export const FETCH_TALKS_FAILURE = 'FETCH_TALKS_FAILURE';

// Chat
export const FETCH_CHAT_REQUEST = 'FETCH_CHAT_REQUEST';
export const FETCH_CHAT_SUCCESS = 'FETCH_CHAT_SUCCESS';
export const FETCH_CHAT_FAILURE = 'FETCH_CHAT_FAILURE';
export const ADD_NEWMESSAGE_REQUEST = 'ADD_NEWMESSAGE_REQUEST';
export const ADD_NEWMESSAGE_SUCCESS = 'ADD_NEWMESSAGE_SUCCESS';
export const ADD_NEWMESSAGE_FAILURE = 'ADD_NEWMESSAGE_FAILURE';

// SignIn
export const SIGNIN_EMAIL_REQUEST = 'SIGNIN_EMAIL_REQUEST';
export const SIGNIN_EMAIL_SUCCESS = 'SIGNIN_EMAIL_SUCCESS';
export const SIGNIN_EMAIL_FAILURE = 'SIGNIN_EMAIL_FAILURE';
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
// Edit account
export const EDIT_ACCOUNT_REQUEST = 'EDIT_ACCOUNT_REQUEST';
export const EDIT_ACCOUNT_SUCCESS = 'EDIT_ACCOUNT_SUCCESS';
export const EDIT_ACCOUNT_FAILURE = 'EDIT_ACCOUNT_FAILURE';
export const EDIT_ACCOUNT_CLEAN = 'EDIT_ACCOUNT_CLEAN';
// Sign off
export const SIGNOFF_REQUEST = 'SIGNOFF_REQUEST';
export const SIGNOFF_SUCCESS = 'SIGNOFF_SUCCESS';
export const SIGNOFF_FAILURE = 'SIGNOFF_FAILURE';
