export const BOOKS_RECEIVED = 'BOOKS_RECEIVED';
export const BOOKS_REQUESTED = 'BOOKS_REQUESTED';
export const BOOKS_REQUEST_FAILED = 'BOOKS_REQUEST_FAILED';
export const UPDATE_BOOK = 'UPDATE_BOOK';
export const REMOVE_BOOK = 'REMOVE_BOOK';
