export const UPDATE_MYBOOKS = 'UPDATE_MYBOOKS';
export const UPDATE_MYBOOKS_RAW = 'UPDATE_MYBOOKS_RAW';
export const UPDATE_BOOK = 'UPDATE_BOOK';
export const FETCH_REQUESTED = 'FETCH_REQUESTED';
export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED';
export const FETCH_FAILED = 'FETCH_FAILED';
